CREATE TABLE phenix.aprta (
  termscode VARCHAR2(6 BYTE) NOT NULL,
  audtdate NUMBER(9) NOT NULL,
  audttime NUMBER(9) NOT NULL,
  audtuser VARCHAR2(8 BYTE) NOT NULL,
  audtorg VARCHAR2(6 BYTE) NOT NULL,
  codedesc VARCHAR2(60 BYTE) NOT NULL,
  swactv NUMBER(*,0) NOT NULL,
  dateinactv NUMBER(9) NOT NULL,
  datelastmn NUMBER(9) NOT NULL,
  swmultpaym NUMBER(*,0) NOT NULL,
  codevat NUMBER(*,0) NOT NULL,
  codedistyp NUMBER(*,0) NOT NULL,
  disdaystr1 NUMBER(3) NOT NULL,
  disdaystr2 NUMBER(3) NOT NULL,
  disdaystr3 NUMBER(3) NOT NULL,
  disdaystr4 NUMBER(3) NOT NULL,
  disdayend1 NUMBER(3) NOT NULL,
  disdayend2 NUMBER(3) NOT NULL,
  disdayend3 NUMBER(3) NOT NULL,
  disdayend4 NUMBER(3) NOT NULL,
  dismthadd1 NUMBER(3) NOT NULL,
  dismthadd2 NUMBER(3) NOT NULL,
  dismthadd3 NUMBER(3) NOT NULL,
  dismthadd4 NUMBER(3) NOT NULL,
  disdayuse1 NUMBER(3) NOT NULL,
  disdayuse2 NUMBER(3) NOT NULL,
  disdayuse3 NUMBER(3) NOT NULL,
  disdayuse4 NUMBER(3) NOT NULL,
  codeduetyp NUMBER(*,0) NOT NULL,
  duedaystr1 NUMBER(3) NOT NULL,
  duedaystr2 NUMBER(3) NOT NULL,
  duedaystr3 NUMBER(3) NOT NULL,
  duedaystr4 NUMBER(3) NOT NULL,
  duedayend1 NUMBER(3) NOT NULL,
  duedayend2 NUMBER(3) NOT NULL,
  duedayend3 NUMBER(3) NOT NULL,
  duedayend4 NUMBER(3) NOT NULL,
  duemthadd1 NUMBER(3) NOT NULL,
  duemthadd2 NUMBER(3) NOT NULL,
  duemthadd3 NUMBER(3) NOT NULL,
  duemthadd4 NUMBER(3) NOT NULL,
  duedayuse1 NUMBER(3) NOT NULL,
  duedayuse2 NUMBER(3) NOT NULL,
  duedayuse3 NUMBER(3) NOT NULL,
  duedayuse4 NUMBER(3) NOT NULL,
  cntentered NUMBER(7) NOT NULL,
  pctduetot NUMBER(9,5) NOT NULL,
  PRIMARY KEY (termscode) USING INDEX (CREATE UNIQUE INDEX phenix.aprta_pk ON phenix.aprta(termscode)    )
);