CREATE TABLE phenix.arrta (
  codeterm VARCHAR2(6 BYTE) NOT NULL,
  audtdate NUMBER(9) NOT NULL,
  audttime NUMBER(9) NOT NULL,
  audtuser VARCHAR2(8 BYTE) NOT NULL,
  audtorg VARCHAR2(6 BYTE) NOT NULL,
  textdesc VARCHAR2(60 BYTE) NOT NULL,
  activesw NUMBER(*,0) NOT NULL,
  inacdate NUMBER(9) NOT NULL,
  lastmntn NUMBER(9) NOT NULL,
  multipaym NUMBER(*,0) NOT NULL,
  vatcodem NUMBER(*,0) NOT NULL,
  disctype NUMBER(*,0) NOT NULL,
  discpct NUMBER(9,5) NOT NULL,
  discnbr NUMBER(3) NOT NULL,
  discday NUMBER(3) NOT NULL,
  ddaystrt1 NUMBER(3) NOT NULL,
  ddaystrt2 NUMBER(3) NOT NULL,
  ddaystrt3 NUMBER(3) NOT NULL,
  ddaystrt4 NUMBER(3) NOT NULL,
  ddayend1 NUMBER(3) NOT NULL,
  ddayend2 NUMBER(3) NOT NULL,
  ddayend3 NUMBER(3) NOT NULL,
  ddayend4 NUMBER(3) NOT NULL,
  dmnthadd1 NUMBER(3) NOT NULL,
  dmnthadd2 NUMBER(3) NOT NULL,
  dmnthadd3 NUMBER(3) NOT NULL,
  dmnthadd4 NUMBER(3) NOT NULL,
  ddayuse1 NUMBER(3) NOT NULL,
  ddayuse2 NUMBER(3) NOT NULL,
  ddayuse3 NUMBER(3) NOT NULL,
  ddayuse4 NUMBER(3) NOT NULL,
  duetype NUMBER(*,0) NOT NULL,
  cntdueday NUMBER(3) NOT NULL,
  duenbrdays NUMBER(3) NOT NULL,
  dudayst1 NUMBER(3) NOT NULL,
  dudayst2 NUMBER(3) NOT NULL,
  dudayst3 NUMBER(3) NOT NULL,
  dudayst4 NUMBER(3) NOT NULL,
  dudayend1 NUMBER(3) NOT NULL,
  dudayend2 NUMBER(3) NOT NULL,
  dudayend3 NUMBER(3) NOT NULL,
  dudayend4 NUMBER(3) NOT NULL,
  dumnthad1 NUMBER(3) NOT NULL,
  dumnthad2 NUMBER(3) NOT NULL,
  dumnthad3 NUMBER(3) NOT NULL,
  dumnthad4 NUMBER(3) NOT NULL,
  dudayuse1 NUMBER(3) NOT NULL,
  dudayuse2 NUMBER(3) NOT NULL,
  dudayuse3 NUMBER(3) NOT NULL,
  dudayuse4 NUMBER(3) NOT NULL,
  dteduesync NUMBER(*,0) NOT NULL,
  dtedscsync NUMBER(*,0) NOT NULL,
  cntentered NUMBER(7) NOT NULL,
  pctduetot NUMBER(9,5) NOT NULL,
  PRIMARY KEY (codeterm) USING INDEX (CREATE UNIQUE INDEX phenix.arrta_pk ON phenix.arrta(codeterm)    )
);