CREATE TABLE phenix.arstobl (
  stmtseq NUMBER(*,0) NOT NULL,
  idcust VARCHAR2(12 BYTE) NOT NULL,
  idinvc VARCHAR2(22 BYTE) NOT NULL,
  audtdate NUMBER(9) NOT NULL,
  audttime NUMBER(9) NOT NULL,
  audtuser VARCHAR2(8 BYTE) NOT NULL,
  audtorg VARCHAR2(6 BYTE) NOT NULL,
  stmtdate NUMBER(9) NOT NULL,
  code VARCHAR2(1 BYTE) NOT NULL,
  rectype VARCHAR2(1 BYTE) NOT NULL,
  idrmit VARCHAR2(24 BYTE) NOT NULL,
  idcustpo VARCHAR2(22 BYTE) NOT NULL,
  idordernbr VARCHAR2(22 BYTE) NOT NULL,
  dateinvc NUMBER(9) NOT NULL,
  datedue NUMBER(9) NOT NULL,
  descinvc VARCHAR2(60 BYTE) NOT NULL,
  trxtypetxt NUMBER(*,0) NOT NULL,
  trxtypeid NUMBER(*,0) NOT NULL,
  amtdue NUMBER(19,3) NOT NULL,
  amtdisc NUMBER(19,3) NOT NULL,
  idcustshpt VARCHAR2(6 BYTE) NOT NULL,
  codeterm VARCHAR2(6 BYTE) NOT NULL,
  datelastst NUMBER(9) NOT NULL,
  "VALUES" NUMBER(*,0) NOT NULL,
  amtinvc NUMBER(19,3) NOT NULL,
  CONSTRAINT arstobl_pk PRIMARY KEY (stmtseq,idinvc,idcust,audtorg)
);