CREATE TABLE phenix.arstnat (
  stmtseq NUMBER(*,0) NOT NULL,
  idnatacct VARCHAR2(12 BYTE) NOT NULL,
  audtdate NUMBER(9) NOT NULL,
  audttime NUMBER(9) NOT NULL,
  audtuser VARCHAR2(8 BYTE) NOT NULL,
  audtorg VARCHAR2(6 BYTE) NOT NULL,
  stmtdate NUMBER(9) NOT NULL,
  swprinted NUMBER(*,0) NOT NULL,
  nameacct VARCHAR2(60 BYTE) NOT NULL,
  textstre1 VARCHAR2(60 BYTE) NOT NULL,
  textstre2 VARCHAR2(60 BYTE) NOT NULL,
  textstre3 VARCHAR2(60 BYTE) NOT NULL,
  textstre4 VARCHAR2(60 BYTE) NOT NULL,
  namecity VARCHAR2(30 BYTE) NOT NULL,
  codestate VARCHAR2(30 BYTE) NOT NULL,
  codepost VARCHAR2(20 BYTE) NOT NULL,
  codectry VARCHAR2(30 BYTE) NOT NULL,
  namectac VARCHAR2(60 BYTE) NOT NULL,
  textphon1 VARCHAR2(30 BYTE) NOT NULL,
  textphon2 VARCHAR2(30 BYTE) NOT NULL,
  textstmt VARCHAR2(45 BYTE) NOT NULL,
  email VARCHAR2(50 BYTE) NOT NULL,
  website VARCHAR2(100 BYTE) NOT NULL,
  ctacphone VARCHAR2(30 BYTE) NOT NULL,
  ctacfax VARCHAR2(30 BYTE) NOT NULL,
  ctacemail VARCHAR2(50 BYTE) NOT NULL,
  delmethod NUMBER(*,0) NOT NULL,
  swbalfwd NUMBER(*,0) NOT NULL,
  amtbgnblf NUMBER(19,3) NOT NULL,
  amtebalfd NUMBER(19,3) NOT NULL,
  amtstmtbl NUMBER(19,3) NOT NULL,
  amtduecur NUMBER(19,3) NOT NULL,
  amtdueag1 NUMBER(19,3) NOT NULL,
  amtdueag2 NUMBER(19,3) NOT NULL,
  amtdueag3 NUMBER(19,3) NOT NULL,
  amtdueag4 NUMBER(19,3) NOT NULL,
  amtduefwd NUMBER(19,3) NOT NULL,
  amtcrlimit NUMBER(19,3) NOT NULL,
  codecurn CHAR(3 BYTE) NOT NULL,
  CONSTRAINT arstnat_pk PRIMARY KEY (stmtseq,idnatacct,audtorg)
);