CREATE TABLE phenix.arstcus (
  stmtseq NUMBER(*,0) NOT NULL,
  idcust VARCHAR2(12 BYTE) NOT NULL,
  audtdate NUMBER(9) NOT NULL,
  audttime NUMBER(9) NOT NULL,
  audtuser VARCHAR2(8 BYTE) NOT NULL,
  audtorg VARCHAR2(6 BYTE) NOT NULL,
  swprinted NUMBER(*,0) NOT NULL,
  swnatstmt NUMBER(*,0) NOT NULL,
  idnatacct VARCHAR2(12 BYTE) NOT NULL,
  stmtdate NUMBER(9) NOT NULL,
  textsnam VARCHAR2(10 BYTE) NOT NULL,
  idgrp VARCHAR2(6 BYTE) NOT NULL,
  swactv NUMBER(*,0) NOT NULL,
  dateinac NUMBER(9) NOT NULL,
  datelastmn NUMBER(9) NOT NULL,
  swhold NUMBER(*,0) NOT NULL,
  datestart NUMBER(9) NOT NULL,
  idppnt VARCHAR2(12 BYTE) NOT NULL,
  codedab VARCHAR2(9 BYTE) NOT NULL,
  codedabrtg VARCHAR2(5 BYTE) NOT NULL,
  datedab NUMBER(9) NOT NULL,
  namecust VARCHAR2(60 BYTE) NOT NULL,
  textstre1 VARCHAR2(60 BYTE) NOT NULL,
  textstre2 VARCHAR2(60 BYTE) NOT NULL,
  textstre3 VARCHAR2(60 BYTE) NOT NULL,
  textstre4 VARCHAR2(60 BYTE) NOT NULL,
  namecity VARCHAR2(30 BYTE) NOT NULL,
  codestte VARCHAR2(30 BYTE) NOT NULL,
  codepstl VARCHAR2(20 BYTE) NOT NULL,
  codectry VARCHAR2(30 BYTE) NOT NULL,
  namectac VARCHAR2(60 BYTE) NOT NULL,
  textphon1 VARCHAR2(30 BYTE) NOT NULL,
  textphon2 VARCHAR2(30 BYTE) NOT NULL,
  codeterr VARCHAR2(6 BYTE) NOT NULL,
  idacctset VARCHAR2(6 BYTE) NOT NULL,
  idautocash VARCHAR2(6 BYTE) NOT NULL,
  idbillcycl VARCHAR2(6 BYTE) NOT NULL,
  idsvcchrg VARCHAR2(6 BYTE) NOT NULL,
  iddlnq VARCHAR2(6 BYTE) NOT NULL,
  codecurn VARCHAR2(3 BYTE) NOT NULL,
  swprtstmt NUMBER(*,0) NOT NULL,
  swprtdlnq NUMBER(*,0) NOT NULL,
  swbalfwd NUMBER(*,0) NOT NULL,
  codeterm VARCHAR2(6 BYTE) NOT NULL,
  idratetype VARCHAR2(2 BYTE) NOT NULL,
  codetaxgrp VARCHAR2(12 BYTE) NOT NULL,
  idtaxregi1 VARCHAR2(20 BYTE) NOT NULL,
  idtaxregi2 VARCHAR2(20 BYTE) NOT NULL,
  idtaxregi3 VARCHAR2(20 BYTE) NOT NULL,
  idtaxregi4 VARCHAR2(20 BYTE) NOT NULL,
  idtaxregi5 VARCHAR2(20 BYTE) NOT NULL,
  taxstts1 NUMBER(*,0) NOT NULL,
  taxstts2 NUMBER(*,0) NOT NULL,
  taxstts3 NUMBER(*,0) NOT NULL,
  taxstts4 NUMBER(*,0) NOT NULL,
  taxstts5 NUMBER(*,0) NOT NULL,
  amtcrlimt NUMBER(19,3) NOT NULL,
  amtbalduet NUMBER(19,3) NOT NULL,
  amtbaldueh NUMBER(19,3) NOT NULL,
  datelastst NUMBER(9) NOT NULL,
  amtlaststt NUMBER(19,3) NOT NULL,
  amtlaststh NUMBER(19,3) NOT NULL,
  dtbegbalfw NUMBER(9) NOT NULL,
  amtbalfwdt NUMBER(19,3) NOT NULL,
  amtbalfwdh NUMBER(19,3) NOT NULL,
  dtlastrval NUMBER(9) NOT NULL,
  amtballarv NUMBER(19,3) NOT NULL,
  cntopeninv NUMBER(7) NOT NULL,
  cntinvpaid NUMBER(7) NOT NULL,
  daystopay NUMBER(7) NOT NULL,
  dateinvchi NUMBER(9) NOT NULL,
  datebalhi NUMBER(9) NOT NULL,
  dateinvhil NUMBER(9) NOT NULL,
  datebalhil NUMBER(9) NOT NULL,
  datelastac NUMBER(9) NOT NULL,
  datelastiv NUMBER(9) NOT NULL,
  datelastcr NUMBER(9) NOT NULL,
  datelastdr NUMBER(9) NOT NULL,
  datelastpa NUMBER(9) NOT NULL,
  datelastdi NUMBER(9) NOT NULL,
  datelastad NUMBER(9) NOT NULL,
  datelastwr NUMBER(9) NOT NULL,
  datelastri NUMBER(9) NOT NULL,
  datelastin NUMBER(9) NOT NULL,
  datelastdq NUMBER(9) NOT NULL,
  idinvchi VARCHAR2(22 BYTE) NOT NULL,
  idinvchily VARCHAR2(22 BYTE) NOT NULL,
  amtinvhit NUMBER(19,3) NOT NULL,
  amtbalhit NUMBER(19,3) NOT NULL,
  amtinvhilt NUMBER(19,3) NOT NULL,
  amtbalhilt NUMBER(19,3) NOT NULL,
  amtlastivt NUMBER(19,3) NOT NULL,
  amtlastcrt NUMBER(19,3) NOT NULL,
  amtlastdrt NUMBER(19,3) NOT NULL,
  amtlastpyt NUMBER(19,3) NOT NULL,
  amtlastdit NUMBER(19,3) NOT NULL,
  amtlastadt NUMBER(19,3) NOT NULL,
  amtlastwrt NUMBER(19,3) NOT NULL,
  amtlastrit NUMBER(19,3) NOT NULL,
  amtlastint NUMBER(19,3) NOT NULL,
  amtinvhih NUMBER(19,3) NOT NULL,
  amtbalhih NUMBER(19,3) NOT NULL,
  amtinvhilh NUMBER(19,3) NOT NULL,
  amtbalhilh NUMBER(19,3) NOT NULL,
  amtlastivh NUMBER(19,3) NOT NULL,
  amtlastcrh NUMBER(19,3) NOT NULL,
  amtlastdrh NUMBER(19,3) NOT NULL,
  amtlastpyh NUMBER(19,3) NOT NULL,
  amtlastdih NUMBER(19,3) NOT NULL,
  amtlastadh NUMBER(19,3) NOT NULL,
  amtlastwrh NUMBER(19,3) NOT NULL,
  amtlastrih NUMBER(19,3) NOT NULL,
  amtlastinh NUMBER(19,3) NOT NULL,
  codeslsp1 VARCHAR2(8 BYTE) NOT NULL,
  codeslsp2 VARCHAR2(8 BYTE) NOT NULL,
  codeslsp3 VARCHAR2(8 BYTE) NOT NULL,
  codeslsp4 VARCHAR2(8 BYTE) NOT NULL,
  codeslsp5 VARCHAR2(8 BYTE) NOT NULL,
  pctsasplt1 NUMBER(9,5) NOT NULL,
  pctsasplt2 NUMBER(9,5) NOT NULL,
  pctsasplt3 NUMBER(9,5) NOT NULL,
  pctsasplt4 NUMBER(9,5) NOT NULL,
  pctsasplt5 NUMBER(9,5) NOT NULL,
  priclist VARCHAR2(6 BYTE) NOT NULL,
  custtype NUMBER(*,0) NOT NULL,
  amtpdue NUMBER(19,3) NOT NULL,
  textstmt VARCHAR2(45 BYTE) NOT NULL,
  email1 VARCHAR2(50 BYTE) NOT NULL,
  email2 VARCHAR2(50 BYTE) NOT NULL,
  website VARCHAR2(100 BYTE) NOT NULL,
  delmethod NUMBER(*,0) NOT NULL,
  ctacphone VARCHAR2(30 BYTE) NOT NULL,
  ctacfax VARCHAR2(30 BYTE) NOT NULL,
  swpartship NUMBER(*,0) NOT NULL,
  hamtbgnblf NUMBER(19,3) NOT NULL,
  hamtebalfd NUMBER(19,3) NOT NULL,
  hamtstmtbl NUMBER(19,3) NOT NULL,
  hamtduecur NUMBER(19,3) NOT NULL,
  hamtdueag1 NUMBER(19,3) NOT NULL,
  hamtdueag2 NUMBER(19,3) NOT NULL,
  hamtdueag3 NUMBER(19,3) NOT NULL,
  hamtdueag4 NUMBER(19,3) NOT NULL,
  hamtduefwd NUMBER(19,3) NOT NULL,
  rbcname VARCHAR2(60 BYTE) NOT NULL,
  rbcstreet1 VARCHAR2(60 BYTE) NOT NULL,
  rbcstreet2 VARCHAR2(60 BYTE) NOT NULL,
  rbcstreet3 VARCHAR2(60 BYTE) NOT NULL,
  rbcstreet4 VARCHAR2(60 BYTE) NOT NULL,
  rbccity VARCHAR2(30 BYTE) NOT NULL,
  rbcstate VARCHAR2(30 BYTE) NOT NULL,
  rbcpstcde VARCHAR2(20 BYTE) NOT NULL,
  rbccntycde VARCHAR2(30 BYTE) NOT NULL,
  cusdecimal NUMBER(*,0) NOT NULL,
  cursymbol CHAR(4 BYTE) NOT NULL,
  "VALUES" NUMBER(*,0) NOT NULL,
  CONSTRAINT arstcus_pk PRIMARY KEY (idcust,stmtseq,audtorg)
);