CREATE TABLE phenix.ber8159_val_transp_transact (
  vat_nom_fichier VARCHAR2(255 BYTE),
  vat_id NUMBER(15),
  vat_pass NUMBER(1),
  vat_vtt_id_existant NUMBER(15),
  vat_vtt_ven_code VARCHAR2(5 BYTE),
  vat_vtt_ven_name VARCHAR2(100 BYTE),
  vat_vtt_cus_code VARCHAR2(20 BYTE),
  vat_vtt_cus_name VARCHAR2(100 BYTE),
  vat_vtt_billed_cus_code VARCHAR2(10 BYTE),
  vat_vtt_billed_cus_name VARCHAR2(100 BYTE),
  vat_vtt_delivery_date DATE,
  vat_vtt_reference_number VARCHAR2(15 BYTE),
  vat_vtt_vts_code VARCHAR2(10 BYTE),
  vat_vtt_vtr_id NUMBER(15),
  vat_vtt_rou_code NUMBER(5),
  vat_vtt_position NUMBER(7,2),
  vat_vtt_weight VARCHAR2(9 BYTE),
  vat_vtt_weight_uom VARCHAR2(3 BYTE),
  vat_vtt_number_of_packages VARCHAR2(7 BYTE),
  vat_vtt_number_of_pallets VARCHAR2(7 BYTE),
  vat_vtt_value VARCHAR2(8 BYTE),
  vat_vtt_message VARCHAR2(100 BYTE),
  vat_vtt_receipt_switch NUMBER(1),
  vat_vtt_number_of_stickers NUMBER(3),
  vat_vtt_shipped_switch NUMBER(1),
  vat_vtt_inh_id NUMBER(15),
  vat_ccr_code NUMBER(5),
  vat_vtt_invoiced_minimum_value NUMBER(7,2),
  vat_vtt_invoiced_trans_amount NUMBER(7,2),
  vat_vtt_skip_invoicing_switch NUMBER(1),
  vat_vtt_provincial_tax_rate NUMBER(6,3),
  vat_vtt_federal_tax_rate NUMBER(6,3),
  vat_vtt_whs_code VARCHAR2(2 BYTE),
  vat_vtt_invoiced_fuel_amount NUMBER(7,2),
  vat_vtt_vtr_invoicing_method VARCHAR2(3 BYTE),
  vat_vtt_vtr_fixed_amount NUMBER(7,2),
  vat_vtt_vtr_minimum_charge NUMBER(7,2),
  vat_vtt_vtr_min_charge_method VARCHAR2(3 BYTE),
  vat_vtt_vtr_min_charge_group VARCHAR2(3 BYTE),
  vat_vtt_vtl_charge_rate NUMBER(8,3),
  vat_vtt_doc_id VARCHAR2(15 BYTE),
  vat_vtt_path_img_original VARCHAR2(500 BYTE),
  vat_vtt_path_img_updated VARCHAR2(500 BYTE),
  vat_vtt_path_img_signed VARCHAR2(500 BYTE),
  vat_vtt_stamp_switch NUMBER(1),
  vat_vtt_signed_switch NUMBER(1),
  vat_vtt_exception_switch NUMBER(1),
  vat_vtt_page_missed VARCHAR2(20 BYTE),
  vat_tdh_to_insert NUMBER(1),
  vat_tdh_route_date DATE,
  vat_tdh_route_trk_code VARCHAR2(8 BYTE),
  vat_tdh_use_code NUMBER(5),
  vat_tdh_use_aide_code NUMBER(5),
  vat_tdh_route_loc_dock_code VARCHAR2(12 BYTE),
  vat_trd_to_insert NUMBER(1),
  vat_vtt_path_img_original_prin VARCHAR2(500 BYTE),
  vat_vtt_path_img_updated_prin VARCHAR2(500 BYTE),
  vat_transporter_ref_cus VARCHAR2(20 BYTE),
  vat_vtt_volume NUMBER(10,3)
);