CREATE TABLE phenix.csc8833_pick_mission_headers (
  pmh_id NUMBER(15) NOT NULL,
  pmh_cus_code NUMBER(10),
  pmh_rou_code NUMBER(5),
  pmh_route_position NUMBER(7,2),
  pmh_route_date DATE,
  pmh_whz_code VARCHAR2(2 BYTE),
  pmh_status VARCHAR2(10 BYTE) NOT NULL,
  pmh_selected_switch NUMBER(1) NOT NULL,
  pmh_use_completion_code NUMBER(5),
  pmh_use_picker_code NUMBER(5),
  pmh_number_of_packages NUMBER(5),
  pmh_ven_code NUMBER(5),
  pmh_type VARCHAR2(1 BYTE) NOT NULL,
  pmh_counter_switch NUMBER(1) NOT NULL,
  pmh_container_reprint_date DATE,
  pmh_start_date DATE,
  pmh_container_id NUMBER(12),
  pmh_container_quantity NUMBER(1),
  pmh_loaded_on_truck_switch NUMBER(1) NOT NULL,
  pmh_whs_picking_code VARCHAR2(2 BYTE) NOT NULL,
  pmh_whs_delivery_code VARCHAR2(2 BYTE) NOT NULL,
  pmh_overstock_switch NUMBER(1) NOT NULL,
  pmh_pco_id NUMBER(15),
  pmh_pal_mission_complet_switch NUMBER(1) NOT NULL,
  pmh_liquidation_switch NUMBER(1) NOT NULL,
  pmh_prw_whz_code VARCHAR2(2 BYTE)
);