CREATE TABLE phenix.fax_logs (
  fax_jobid VARCHAR2(20 BYTE),
  fax_parentjobid VARCHAR2(20 BYTE),
  fax_submissiontime DATE,
  fax_scheduled DATE,
  fax_status VARCHAR2(257 BYTE),
  fax_errordesc VARCHAR2(257 BYTE),
  fax_errorcode VARCHAR2(12 BYTE),
  fax_starttime DATE,
  fax_endtime DATE,
  fax_device VARCHAR2(257 BYTE),
  fax_dialednumber VARCHAR2(257 BYTE),
  fax_csid VARCHAR2(257 BYTE),
  fax_tsid VARCHAR2(257 BYTE),
  fax_pages VARCHAR2(18 BYTE),
  fax_totalpages VARCHAR2(18 BYTE),
  fax_queuefilename VARCHAR2(257 BYTE),
  fax_document VARCHAR2(257 BYTE),
  fax_filesize VARCHAR2(18 BYTE),
  fax_retries VARCHAR2(18 BYTE),
  fax_servercoverpage VARCHAR2(257 BYTE),
  fax_coverpagesubject VARCHAR2(257 BYTE),
  fax_coverpagenote VARCHAR2(257 BYTE),
  fax_username VARCHAR2(257 BYTE),
  fax_sendername VARCHAR2(257 BYTE),
  fax_senderfaxnumber VARCHAR2(257 BYTE),
  fax_sendercompany VARCHAR2(257 BYTE),
  fax_senderstreet VARCHAR2(257 BYTE),
  fax_sendercity VARCHAR2(257 BYTE),
  fax_senderzipcode VARCHAR2(257 BYTE),
  fax_sendercountryregion VARCHAR2(257 BYTE),
  fax_sendertitle VARCHAR2(257 BYTE),
  fax_senderdepartment VARCHAR2(257 BYTE),
  fax_senderoffice VARCHAR2(257 BYTE),
  fax_senderhomephone VARCHAR2(257 BYTE),
  fax_senderofficephone VARCHAR2(257 BYTE),
  fax_senderemail VARCHAR2(257 BYTE),
  fax_recipientname VARCHAR2(257 BYTE),
  fax_recipientfaxnumber VARCHAR2(257 BYTE),
  fax_recipientcompany VARCHAR2(257 BYTE),
  fax_recipientstreet VARCHAR2(257 BYTE),
  fax_recipientcity VARCHAR2(257 BYTE),
  fax_recipientzipcode VARCHAR2(257 BYTE),
  fax_recipientcountryregion VARCHAR2(257 BYTE),
  fax_recipienttitle VARCHAR2(257 BYTE),
  fax_recipientdepartment VARCHAR2(257 BYTE),
  fax_recipientoffice VARCHAR2(257 BYTE),
  fax_recipienthomephone VARCHAR2(257 BYTE),
  fax_recipientofficephone VARCHAR2(257 BYTE),
  fax_recipientemail VARCHAR2(257 BYTE),
  fax_billingcode VARCHAR2(257 BYTE)
);