CREATE TABLE phenix.inh_qtab (
  q_name VARCHAR2(30 BYTE),
  msgid RAW(16) NOT NULL,
  corrid VARCHAR2(128 BYTE),
  "PRIORITY" NUMBER,
  "STATE" NUMBER,
  "DELAY" TIMESTAMP,
  expiration NUMBER,
  time_manager_info TIMESTAMP,
  local_order_no NUMBER,
  chain_no NUMBER,
  cscn NUMBER,
  dscn NUMBER,
  enq_time TIMESTAMP,
  enq_uid VARCHAR2(30 BYTE),
  enq_tid VARCHAR2(30 BYTE),
  deq_time TIMESTAMP,
  deq_uid VARCHAR2(30 BYTE),
  deq_tid VARCHAR2(30 BYTE),
  retry_count NUMBER,
  exception_qschema VARCHAR2(30 BYTE),
  exception_queue VARCHAR2(30 BYTE),
  step_no NUMBER,
  recipient_key NUMBER,
  dequeue_msgid RAW(16),
  sender_name VARCHAR2(30 BYTE),
  sender_address VARCHAR2(1024 BYTE),
  sender_protocol NUMBER,
  "USER_DATA" phenix.inh_queue_info,
  user_prop sys.anydata,
  PRIMARY KEY (msgid)
);