CREATE TABLE phenix.maz_gcl9522 (
  cus_code NUMBER(10) NOT NULL,
  cus_prv_resides_in_code VARCHAR2(2 BYTE) NOT NULL,
  cus_use_code NUMBER(5) NOT NULL,
  cus_active_schedules_switch NUMBER(1) NOT NULL,
  cus_address VARCHAR2(45 BYTE) NOT NULL,
  cus_admin_method VARCHAR2(1 BYTE) NOT NULL,
  cus_ar_payment_switch NUMBER(1) NOT NULL,
  cus_city VARCHAR2(30 BYTE) NOT NULL,
  cus_creation_date DATE NOT NULL,
  cus_credit_control_switch NUMBER(1) NOT NULL,
  cus_credit_status VARCHAR2(1 BYTE) NOT NULL,
  cus_deleted_switch NUMBER(1) NOT NULL,
  cus_interest NUMBER(6,3) NOT NULL,
  cus_inv_head_office_switch NUMBER(1) NOT NULL,
  cus_invoice_copies NUMBER(2) NOT NULL,
  cus_language_flag VARCHAR2(1 BYTE) NOT NULL,
  cus_multi_vend_drop_switch NUMBER(1) NOT NULL,
  cus_name VARCHAR2(30 BYTE) NOT NULL,
  cus_order_required_switch NUMBER(1) NOT NULL,
  cus_open_quotation_switch NUMBER(1) NOT NULL,
  cus_postal_code VARCHAR2(10 BYTE) NOT NULL,
  cus_print_ticket_switch NUMBER(1) NOT NULL,
  cus_projected_sales_amount NUMBER(12,2) NOT NULL,
  cus_ranking VARCHAR2(1 BYTE) NOT NULL,
  cus_substitution_switch NUMBER(1) NOT NULL,
  cus_surcharge_switch NUMBER(1) NOT NULL,
  cus_telephone NUMBER(11) NOT NULL,
  cus_volume_rebate_switch NUMBER(1) NOT NULL,
  cus_cus_code NUMBER(10),
  cus_cgr_code NUMBER(3),
  cus_dgt_code NUMBER(5),
  cus_prv_delivers_in_code VARCHAR2(2 BYTE),
  cus_qty_code NUMBER(5),
  cus_srt_code NUMBER(3),
  cus_trt_code NUMBER(2),
  cus_use_telemark_code NUMBER(5),
  cus_alt_name VARCHAR2(30 BYTE),
  cus_alcohol_permit VARCHAR2(15 BYTE),
  cus_customer_alpha_index VARCHAR2(15 BYTE),
  cus_credit_limit NUMBER(9,2),
  cus_cigarette_counter NUMBER(9),
  cus_date_last_paid DATE,
  cus_deliver_to_address VARCHAR2(45 BYTE),
  cus_deliver_to_city VARCHAR2(30 BYTE),
  cus_deliver_to_name VARCHAR2(30 BYTE),
  cus_deliver_to_postal_code VARCHAR2(10 BYTE),
  cus_duns_number VARCHAR2(13 BYTE),
  cus_fax_number NUMBER(11),
  cus_latitude NUMBER(7,4),
  cus_longitude NUMBER(7,4),
  cus_terms VARCHAR2(6 BYTE),
  cus_tobacco_permit VARCHAR2(15 BYTE),
  cus_active_schedule_end_date DATE NOT NULL,
  cus_active_schedule_start_date DATE NOT NULL,
  cus_surcharge_per_delivery NUMBER(7,2),
  cus_federal_tax_number VARCHAR2(15 BYTE),
  cus_provincial_tax_number VARCHAR2(18 BYTE),
  cus_vrg_code NUMBER(3),
  cus_print_profile_switch NUMBER(1) NOT NULL,
  cus_pty_code NUMBER(3),
  cus_store_num VARCHAR2(10 BYTE),
  cus_federal_tax_exempt_switch NUMBER(1) NOT NULL,
  cus_province_tax_exempt_switch NUMBER(1) NOT NULL,
  cus_whs_code VARCHAR2(2 BYTE) NOT NULL,
  cus_edi_partner_identity VARCHAR2(20 BYTE),
  cus_vendor_identification VARCHAR2(30 BYTE),
  cus_single_spec_order_switch NUMBER(1) NOT NULL,
  cus_car_code NUMBER(5),
  cus_naz_nac_code NUMBER(4),
  cus_naz_zone_code NUMBER(3),
  cus_elimination_date DATE,
  cus_modification_date DATE NOT NULL,
  cus_reb_on_drop_terms_switch NUMBER(1) NOT NULL,
  cus_reb_on_drop_avr_switch NUMBER(1) NOT NULL,
  cus_reb_on_whouse_avr_switch NUMBER(1) NOT NULL,
  cus_broker_id NUMBER(6),
  cus_transport_allocation NUMBER(6,3),
  cus_generate_synch_file_switch NUMBER(1) NOT NULL,
  cus_edi_product_valid_flag VARCHAR2(1 BYTE) NOT NULL,
  cus_prebook_for_branch_switch NUMBER(1) NOT NULL,
  cus_gen_vol_rebate_cr_switch NUMBER(1) NOT NULL,
  cus_pgs_publish_price_switch NUMBER(1) NOT NULL,
  cus_pos_files_type VARCHAR2(3 BYTE),
  cus_corporate_name VARCHAR2(30 BYTE) NOT NULL,
  cus_invoice_method VARCHAR2(3 BYTE) NOT NULL,
  cus_handling_amount NUMBER(7,2) NOT NULL,
  cus_fsg_code NUMBER(5),
  cus_dcg_code NUMBER(5),
  cus_minimum_profit_amount NUMBER(7,2),
  cus_bursary_amount NUMBER(7,2),
  cus_bursary_end_date DATE,
  cus_loan_interest_amount NUMBER(7,2),
  cus_loan_end_date DATE,
  cus_transport_contribution NUMBER(7,2) NOT NULL,
  cus_minimum_profit_percent NUMBER(6,3),
  cus_dsc_code NUMBER(3),
  cus_minimum_delivery_charge NUMBER(7,2) NOT NULL,
  cus_deliver_telephone NUMBER(11),
  cus_dairy_permit VARCHAR2(15 BYTE),
  cus_block_quotation_pr_switch NUMBER(1) NOT NULL,
  cus_profit_in_deliv_switch NUMBER(1) NOT NULL,
  cus_print_inv_by_line_switch NUMBER(1) NOT NULL,
  cus_ovg_code NUMBER(5),
  cus_recalc_price_at_inv_switch NUMBER(1) NOT NULL,
  cus_last_balance_dollars NUMBER(7,2) NOT NULL,
  cus_last_balance_points NUMBER(5) NOT NULL,
  cus_last_balance_date DATE,
  cus_vtt_stamp_required_switch NUMBER(1) NOT NULL,
  cus_invoice_pallets_switch NUMBER(1) NOT NULL,
  cus_inv_pal_hd_office_switch NUMBER(1) NOT NULL,
  cus_pug_code NUMBER(5),
  cus_cdk_code VARCHAR2(4 BYTE),
  cus_combined_tr_invoice_switch NUMBER(1) NOT NULL,
  cus_detail_tr_invoice_switch NUMBER(1) NOT NULL,
  cus_growth_alloc_percent NUMBER(6,3) NOT NULL,
  cus_additional_alloc_percent NUMBER(6,3) NOT NULL,
  cus_whouse_vol_alloc_percent NUMBER(6,3) NOT NULL,
  cus_drop_volume_alloc_percent NUMBER(6,3) NOT NULL,
  cus_internal_admin_percent NUMBER(6,3) NOT NULL,
  cus_past_due_grace_days NUMBER(3) NOT NULL,
  cus_incl_price_on_route_switch NUMBER(1) NOT NULL,
  cus_pick_by_prw_zone_switch NUMBER(1) NOT NULL,
  cus_str_code VARCHAR2(10 BYTE),
  cus_cat_code NUMBER(2)
);