CREATE GLOBAL TEMPORARY TABLE phenix.temporary_site_sales_summaries (
  tsss_sit_code NUMBER(10) NOT NULL,
  tsss_ssch_code VARCHAR2(15 BYTE) NOT NULL,
  tsss_ssch_start_date DATE NOT NULL,
  tsss_ssch_end_date DATE NOT NULL,
  tsss_ssch_current_week NUMBER NOT NULL,
  tsss_ssch_total_week NUMBER NOT NULL,
  tsss_commitment_code NUMBER(10),
  tsss_commitment_description VARCHAR2(30 BYTE) NOT NULL,
  tsss_commitment_section VARCHAR2(2 BYTE) NOT NULL,
  tsss_commitment_type VARCHAR2(4 BYTE) NOT NULL,
  tsss_period_start_date DATE,
  tsss_period_end_date DATE,
  tsss_period_purchase NUMBER NOT NULL,
  tsss_period_average NUMBER NOT NULL,
  tsss_period_commitment_wkly NUMBER NOT NULL,
  tsss_period_commitment NUMBER NOT NULL,
  tsss_period_difference NUMBER NOT NULL,
  tsss_period_diff_percent NUMBER NOT NULL,
  tsss_to_date_start_date DATE,
  tsss_to_date_end_date DATE,
  tsss_to_date_purchase NUMBER NOT NULL,
  tsss_to_date_average NUMBER NOT NULL,
  tsss_to_date_commitment_wkly NUMBER NOT NULL,
  tsss_to_date_commitment NUMBER NOT NULL,
  tsss_to_date_difference NUMBER NOT NULL,
  tsss_to_date_diff_percent NUMBER NOT NULL
)
ON COMMIT DELETE ROWS;