CREATE TABLE phenix.temporary_multi_warehouses (
  tmw_id NUMBER(15) NOT NULL,
  tmw_tmp_tch_id NUMBER(15) NOT NULL,
  tmw_tmp_prd_code VARCHAR2(10 BYTE) NOT NULL,
  tmw_whs_code VARCHAR2(2 BYTE) NOT NULL,
  tmw_whs_name VARCHAR2(30 BYTE) NOT NULL,
  tmw_prw_replenish_quantity NUMBER(8,3),
  tmw_prw_replenish_coefficient NUMBER(6,3),
  tmw_prw_replenish_point NUMBER(8,3),
  tmw_prw_items_per_pallet NUMBER(5),
  tmw_prw_items_per_row NUMBER(3),
  tmw_pod_avr NUMBER(7,2),
  tmw_pod_consignment_amount NUMBER(7,2),
  tmw_pod_cost_1 NUMBER(7,2),
  tmw_pod_cost_2 NUMBER(7,2),
  tmw_pod_cost_3 NUMBER(7,2),
  tmw_pod_cost_4 NUMBER(7,2),
  tmw_pod_manual_discount NUMBER(5,2),
  tmw_pod_pty_code NUMBER(3),
  tmw_pod_vpr_end_date DATE,
  tmw_pod_vpr_start_date DATE,
  tmw_vpr_freegood_quantity NUMBER,
  tmw_vpr_freegood_volume NUMBER,
  tmw_vpr_reclaim_ven_code NUMBER(5),
  tmw_vpr_reclaim_reference VARCHAR2(15 BYTE),
  tmw_vpr_reclaim_message VARCHAR2(100 BYTE),
  tmw_vpr_alloc_3_applied_on NUMBER(1),
  tmw_vpr_allocation_3 NUMBER(7,2),
  tmw_vpr_match_cost_3_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_vpr_match_cost_3_swi_ck CHECK (tmw_vpr_match_cost_3_switch IN (0, 1)),
  tmw_pod_pod_poh_id NUMBER(15),
  tmw_pod_pod_line_number NUMBER(4),
  tmw_pod_allocation_1 NUMBER(7,2),
  tmw_pod_allocation_2 NUMBER(7,2),
  tmw_pod_allocation_3 NUMBER(7,2),
  tmw_pod_alloc_1_applied_on NUMBER(1),
  tmw_pod_alloc_2_applied_on NUMBER(1),
  tmw_pod_alloc_3_applied_on NUMBER(1),
  tmw_pod_max_quantity_allowed NUMBER(7),
  tmw_pod_max_weight_allowed NUMBER(9,3),
  tmw_pod_ven_code NUMBER(5),
  tmw_pod_reclaim_message VARCHAR2(100 BYTE),
  tmw_pod_reclaim_reference VARCHAR2(15 BYTE),
  tmw_pod_match_cost_1_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_pod_match_cost_1_swi_ck CHECK (tmw_pod_match_cost_1_switch IN (0, 1)),
  tmw_pod_match_cost_2_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_pod_match_cost_2_swi_ck CHECK (tmw_pod_match_cost_2_switch IN (0, 1)),
  tmw_pod_match_cost_3_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_pod_match_cost_3_swi_ck CHECK (tmw_pod_match_cost_3_switch IN (0, 1)),
  tmw_pod_match_cost NUMBER(7,2),
  tmw_pod_disc_cost_affected NUMBER(1),
  tmw_pod_quantity_freegood NUMBER(7),
  tmw_pod_quantity_ordered NUMBER(7),
  tmw_pod_quantity_interco NUMBER(7),
  tmw_pod_quantity_suggested NUMBER(7),
  tmw_pod_weight_freegood NUMBER(9,3),
  tmw_pod_weight_ordered NUMBER(9,3),
  tmw_pod_weight_interco NUMBER(9,3),
  tmw_pod_weight_suggested NUMBER(9,3),
  tmw_cod_total_quantity_prebook NUMBER(7),
  tmw_cod_total_weight_prebook NUMBER(9,3),
  tmw_cod_prebook_bef_next_cycle NUMBER,
  tmw_pod_total_open_prebook_fd NUMBER,
  tmw_pod_total_open_prebook_dc NUMBER,
  tmw_pod_bef_next_deliv_pbk_dc NUMBER,
  tmw_cod_special_left_quantity NUMBER(7),
  tmw_cod_special_left_weight NUMBER(9,3),
  tmw_verified_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_verified_swi_ck CHECK (tmw_verified_switch IN (0, 1)),
  tmw_promo_end_next_cyc_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_promo_end_next_cyc_swi_ck CHECK (tmw_promo_end_next_cyc_switch IN (0, 1)),
  tmw_cod_prebook_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_cod_prebook_swi_ck CHECK (tmw_cod_prebook_switch IN (0, 1)),
  tmw_override_growth_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_override_growth_swi_ck CHECK (tmw_override_growth_switch IN (0, 1)),
  tmw_old_quantity_suggested NUMBER(7),
  tmw_old_weight_suggested NUMBER(9,3),
  tmw_old_freegood_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_freegood_swi_ck CHECK (tmw_old_freegood_switch IN (0, 1)),
  tmw_old_ordered_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_ordered_swi_ck CHECK (tmw_old_ordered_switch IN (0, 1)),
  tmw_old_interco_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_interco_swi_ck CHECK (tmw_old_interco_switch IN (0, 1)),
  tmw_old_manual_disc_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_manual_disc_swi_ck CHECK (tmw_old_manual_disc_switch IN (0, 1)),
  tmw_old_reclaim_info_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_reclaim_info_swi_ck CHECK (tmw_old_reclaim_info_switch IN (0, 1)),
  tmw_old_verified_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_old_verified_swit_ck CHECK (tmw_old_verified_switch IN (0, 1)),
  tmw_prd_qty_on_hand NUMBER,
  tmw_prd_qty_available NUMBER,
  tmw_prd_qty_damaged NUMBER,
  tmw_prd_qty_on_cust_order NUMBER,
  tmw_prd_qty_on_open_pod NUMBER,
  tmw_prd_conv_replenish_qty NUMBER,
  tmw_prd_conv_replenish_point NUMBER,
  tmw_prd_conv_replenish_coeff NUMBER,
  tmw_week_average_sales NUMBER,
  tmw_average_inventory_per_week NUMBER,
  tmw_caps_stats_done_switch NUMBER(1) DEFAULT 0 NOT NULL,
  tmw_pod_pige_prebook_left NUMBER,
  tmw_prw_purchasable_switch NUMBER(1) CONSTRAINT tmw_prw_purchasable_swi_ck CHECK (tmw_prw_purchasable_switch IN (0, 1)),
  tmw_prw_pickable_switch NUMBER(1) CONSTRAINT tmw_prw_pickable_swi_ck CHECK (tmw_prw_pickable_switch IN (0, 1)),
  tmw_next_order_limit_date DATE,
  tmw_pod_list NUMBER(7,2),
  tmw_prd_ctg_code NUMBER(5),
  tmw_prd_catalog_sequence_code NUMBER(5),
  tmw_prd_ven_code NUMBER(5),
  tmw_pige_or_not_chosen_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_pige_or_not_chosen_swi_ck CHECK (tmw_pige_or_not_chosen_switch IN (0, 1)),
  tmw_interco_to_validate_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_interco_to_validate_swi_ck CHECK (tmw_interco_to_validate_switch IN (0, 1)),
  tmw_prw_whz_code VARCHAR2(2 BYTE),
  tmw_whz_description VARCHAR2(30 BYTE),
  tmw_original_qty_suggested NUMBER(7),
  tmw_original_wght_suggested NUMBER(9,3),
  tmw_discount_cost_1 NUMBER(7,2),
  tmw_discount_cost_2 NUMBER(7,2),
  tmw_discount_cost_3 NUMBER(7,2),
  tmw_discount_cost_4 NUMBER(7,2),
  tmw_discount_match_cost NUMBER(7,2),
  tmw_initial_price_calc_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_initial_price_calc_swi_ck CHECK (tmw_initial_price_calc_switch IN (0, 1)),
  tmw_prw_shr_code NUMBER(3),
  tmw_shr_fill_rate_switch NUMBER(1) CONSTRAINT tmw_shr_fill_rate_swi_ck CHECK (tmw_shr_fill_rate_switch IN (0, 1)),
  tmw_shr_description VARCHAR2(30 BYTE),
  tmw_inv_min_qty_wght NUMBER,
  tmw_inv_max_qty_wght NUMBER,
  tmw_total_products NUMBER(10),
  tmw_total_order_weight NUMBER(11,3),
  tmw_total_order_volume NUMBER(11,3),
  tmw_total_order NUMBER(10,2),
  tmw_total_number_of_palettes NUMBER(7,2),
  tmw_total_prebook_quantity NUMBER(7),
  tmw_total_prebook_weight NUMBER(8,3),
  tmw_total_special_quantity NUMBER(7),
  tmw_total_special_weight NUMBER(8,3),
  tmw_interco_generated_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_interco_generated_swi_ck CHECK (tmw_interco_generated_switch IN (0, 1)),
  tmw_qty_interco_link_pod_in NUMBER,
  tmw_qty_interco_link_pod_out NUMBER,
  tmw_inv_expiry_date DATE,
  tmw_cod_preb_bef_next_cycle_fd NUMBER,
  tmw_cod_preb_bef_next_cycle_dc NUMBER,
  tmw_pod_added_transp_amount NUMBER(11,6) DEFAULT 0 NOT NULL,
  tmw_pod_match_cost_freight NUMBER(7,2),
  tmw_prw_sellable_switch NUMBER(1) CONSTRAINT tmw_prw_sellable_switch_ck CHECK (tmw_prw_sellable_switch IN (0, 1)),
  tmw_contract_switch NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT tmw_contract_switch_ck CHECK (TMW_CONTRACT_SWITCH IN (0,1)),
  tmw_round_per_pallet_percent NUMBER(6,3),
  tmw_round_per_row_percent NUMBER(6,3),
  tmw_replenish_nb_of_week NUMBER(3,1),
  tmw_whs_sequence NUMBER(2) DEFAULT 1 NOT NULL,
  tmw_prd_qty_rma NUMBER,
  CONSTRAINT tmw_pk PRIMARY KEY (tmw_id),
  CONSTRAINT tmw_prw_fk FOREIGN KEY (tmw_tmp_prd_code,tmw_whs_code) REFERENCES phenix.product_warehouses (prw_prd_code,prw_whs_code) ON DELETE CASCADE,
  CONSTRAINT tmw_tmp_fk FOREIGN KEY (tmw_tmp_tch_id,tmw_tmp_prd_code) REFERENCES phenix.temporary_multi_products (tmp_tch_id,tmp_prd_code) ON DELETE CASCADE
);
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_inv_expiry_date IS 'Indique la plus ancienne date d''expiration du produit';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_prw_sellable_switch IS 'Indique si cet entrepôt peut vendre le produit';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_contract_switch IS 'Indique s''il y a des contrats qui respectent les règles pour ce produit / entrepôt';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_round_per_pallet_percent IS 'Indique le pourcentage maximum pouvant être ajouté à la quantité suggérée s''il permet l''arrondissement à la palette suivante lors des commandes d''achat';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_round_per_row_percent IS 'Indique le pourcentage maximum pouvant être ajouté à la quantité suggérée s''il permet l''arrondissement à la rangée suivante lors des commandes d''achat';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_replenish_nb_of_week IS 'Indique le nombre de semaines d''inventaire nécessaire en entrepôt pour ne pas commander';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_whs_sequence IS 'Indique ordre de tri des entrepôts';
COMMENT ON COLUMN phenix.temporary_multi_warehouses.tmw_prd_qty_rma IS 'Indique la quantité en retour marchandise attendue';