CREATE OR REPLACE PACKAGE phenix.ACCPAC_REPORT_PACK IS

FUNCTION LOAD_TEMP_ACCPAC_FUNC
RETURN PLS_INTEGER;

FUNCTION LOAD_TEMP_ACCPAC_FROM_AR_FUNC
RETURN PLS_INTEGER;

FUNCTION LOAD_TEMP_ACCPAC_FROM_AP_FUNC
RETURN PLS_INTEGER;

END ACCPAC_REPORT_PACK;

 
/