CREATE OR REPLACE PACKAGE phenix.AUTO_PICK_REPORT_PACK AS

FUNCTION GET_BRN_NAME_FUNC(
	p_brn_code IN NUMBER
)
RETURN VARCHAR2 ;

FUNCTION GET_BRN_OR_VEN_NAME_FUNC(		--fre737
	p_brn_code IN NUMBER,
	p_ven_code IN NUMBER,
	p_language IN VARCHAR DEFAULT 'F'
)
RETURN VARCHAR2;

FUNCTION GET_ROU_POSITION_FUNC(		--fre737
	p_cus_code IN NUMBER,
	p_rou_code IN NUMBER,
	p_rou_date IN DATE
)
RETURN NUMBER;

END AUTO_PICK_REPORT_PACK;
/