CREATE OR REPLACE PACKAGE phenix.CONTEXT_PACK AS

PROCEDURE RESET_CONTEXT_USE_SOURCE_PROC;
PROCEDURE GET_CONTEXT_CUSTOMER_PROC(
  p_cus_code  OUT NUMBER
);
PROCEDURE GET_CONTEXT_ENTITY_PROC(
  p_entity      OUT VARCHAR2,
  p_code_or_id  OUT VARCHAR2
);
PROCEDURE GET_CONTEXT_SOURCE_PROC(
  p_source  OUT VARCHAR2
);
PROCEDURE GET_CONTEXT_USER_PROC(
  p_use_code  OUT NUMBER
);
PROCEDURE SET_CONTEXT_ENTITY_PROC(
  p_entity      IN VARCHAR2,
  p_code_or_id  IN VARCHAR2
);
PROCEDURE SET_CONTEXT_SOURCE_PROC(
  p_source  IN VARCHAR2
);
PROCEDURE SET_CONTEXT_USER_PROC(
  p_use_code  IN NUMBER
);
PROCEDURE RESET_CONTEXTS_PROC;

END CONTEXT_PACK;
/