CREATE OR REPLACE PACKAGE phenix.DOC_OPERATION_PACK AS

FUNCTION GET_FILE_SIZE_FUNC(
  p_doc_code IN documents.doc_code%TYPE
)
RETURN NUMBER;

FUNCTION EXPORT_TO_FILE_FUNC(
  p_doc_code  IN documents.doc_code%TYPE,
  p_directory IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION REMOVE_PATH_FILE_FUNC(
  p_file_name IN VARCHAR2
)
RETURN VARCHAR2;

PROCEDURE UPLOAD_DOCUMENTS_PROC(
  p_jsc_id IN job_schedules.jsc_id%TYPE
);

END DOC_OPERATION_PACK;
/