CREATE OR REPLACE PACKAGE phenix.DSD_OPERATION_PACK IS

PROCEDURE PURGE_PROC(
    p_vds_id                    IN CUSTOMER_DROP_STATEMENTS.CDS_VDS_ID%TYPE,
    p_cus_code                  IN CUSTOMER_DROP_STATEMENTS.CDS_CUS_CODE%TYPE,
    p_reference_number          IN CUSTOMER_DROP_STATEMENTS.CDS_REFERENCE_NUMBER%TYPE
);

PROCEDURE PURGE_PROC(
    p_vds_id                    IN CUSTOMER_DROP_DETAILS.CDD_CDS_VDS_ID%TYPE,
    p_cus_code                  IN CUSTOMER_DROP_DETAILS.CDD_CDS_CUS_CODE%TYPE,
    p_reference_number          IN CUSTOMER_DROP_DETAILS.CDD_CDS_REFERENCE_NUMBER%TYPE,
    p_line_number               IN CUSTOMER_DROP_DETAILS.CDD_LINE_NUMBER%TYPE
);

PROCEDURE PURGE_PROC(
    p_inh_id                    IN INVOICE_HEADERS.INH_ID%TYPE
);


END DSD_OPERATION_PACK;
 
/