CREATE OR REPLACE PACKAGE phenix.EDI_882_TRANSFORM_PACK IS

PROCEDURE SET_DETERMINE_WHS_PROC;
PROCEDURE CREATE_TESH_PROC;
PROCEDURE CREATE_TESA_PROC;
PROCEDURE CREATE_TESS_PROC;
PROCEDURE TSTA_TRANSFORM_PROC;
END EDI_882_TRANSFORM_PACK;
/