CREATE OR REPLACE PACKAGE phenix.FAX_PACK IS

PROCEDURE SENDFAX_PROC(P_FILENAME IN VARCHAR2, P_FAXNUMBER IN VARCHAR2);
PROCEDURE SENDFAXALL_PROC(P_JSC_ID IN NUMBER);
PROCEDURE CONVERTFAX_PROC;
PROCEDURE UPDATEFAXSTATUS_PROC;
FUNCTION GET_FAX_DATE_FUNC(P_ID IN VARCHAR2) RETURN DATE;
PROCEDURE PURGE_FAX_LOG_PROC (P_JSC_ID IN NUMBER);
PROCEDURE SENDFAXALL11g_PROC;

END FAX_PACK;
/