CREATE OR REPLACE PACKAGE phenix.GENERATEDOC_PACK IS

   PROCEDURE GENERATE_STYLE_PROC;
   PROCEDURE GENERATE_SECURITY_PROC;
   PROCEDURE GENERATE_INDEX_PROC;
   PROCEDURE GENERATE_MENU_PROC(P_DATE_START IN DATE);
   PROCEDURE GENERATE_SUMMARY_PROC(P_DATE_START IN DATE);
   PROCEDURE GENERATE_DIAGRAM_PROC;
   PROCEDURE GENERATE_DIAGDTL_PROC;
   PROCEDURE GENERATE_INDEXENT_PROC;
   PROCEDURE GENERATE_MENUENT_PROC;
   PROCEDURE GENERATE_SUMENT_PROC;
   PROCEDURE GENERATE_ENTITY_PROC;
   PROCEDURE GENERATE_ENTLIST_PROC;
   PROCEDURE GENERATE_ENTDTL_PROC(P_DATE_START IN DATE);
   PROCEDURE GENERATE_DOMAIN_PROC;
   PROCEDURE GENERATE_DOMLIST_PROC;
   PROCEDURE GENERATE_DOMDTL_PROC(P_DATE_START IN DATE);
   PROCEDURE GENERATE_LOAD_PROC;
   PROCEDURE GENERATE_LOADLIST_PROC;
   PROCEDURE GENERATE_LOADDTL_PROC;
   PROCEDURE GENERATE_DOCUMENTATION_PROC;
   PROCEDURE GENERATE_DOC_MODIF_PROC(P_DATE_START IN DATE);

END GENERATEDOC_PACK;
/