CREATE OR REPLACE PACKAGE phenix.HTM_PACK IS

PROCEDURE TAKE_PICTURE_PROC(
    p_jsc_id                        IN JOB_SCHEDULES.JSC_ID%TYPE
);

PROCEDURE COMPARE_REPORT_PROC(
    p_at_date                       IN HISTORY_TIMELINE.HTM_AT_DATE%TYPE);

END HTM_PACK;
/