CREATE OR REPLACE PACKAGE phenix.IMP_STATS_INTERFACE_PACK IS

PROCEDURE GEN_IMP_STATS_PROC
	(P_JSC_ID IN NUMBER
	);
PROCEDURE EXTRACT_IMP_STATS_PROC --BER3573
	(p_date 				IN DATE,
	p_crt_code_1	IN NUMBER,
	p_crt_code_2	IN NUMBER,
	p_crt_code_3	IN NUMBER,
	p_whs_code 		IN VARCHAR2
	);

END IMP_STATS_INTERFACE_PACK;
/