CREATE OR REPLACE PACKAGE phenix.INVOICING_REPORT_PACK IS

FUNCTION GET_DISPLAY_TAX_FUNC
 (P_FED_TAX IN NUMBER
 ,P_PROV_TAX IN NUMBER
 ) RETURN VARCHAR2;

FUNCTION GET_DISPLAY_TAX_CVI_FUNC
 (P_FED_TAX IN NUMBER
 ,P_PROV_TAX IN NUMBER
 ) RETURN VARCHAR2;
END INVOICING_REPORT_PACK;
/