CREATE OR REPLACE PACKAGE phenix.LARGE_OBJECT_PACK AS

PROCEDURE WRITE_TEMPORARY_INFO_PROC(
  p_process_name IN VARCHAR2
);

FUNCTION GET_LENGTH_FUNC(
  p_content IN BLOB
)
RETURN NUMBER;

PROCEDURE EXPORT_TO_FILE_PROC(
  p_content   IN BLOB,
  p_directory IN VARCHAR2,
  p_file_name IN VARCHAR2
);

FUNCTION LOAD_FROM_FILE_FUNC(
  p_directory IN VARCHAR2,
  p_file_name IN VARCHAR2
)
RETURN BLOB;

FUNCTION COMPRESS_FUNC(
  p_uncompressed IN BLOB
)
RETURN BLOB;

PROCEDURE COMPRESS_PROC(
  p_directory     IN VARCHAR2,
  p_file_name     IN VARCHAR2,
  p_new_file_name IN VARCHAR2
);

END LARGE_OBJECT_PACK;
/