CREATE OR REPLACE PACKAGE phenix.LOAD_DATA_PACK IS

PROCEDURE LOAD_ERROR_CODES_PROC;
PROCEDURE LOAD_MENU_ITEMS_PROC;
PROCEDURE LOAD_MENU_SECURITY_PROC;
PROCEDURE LOAD_SECURITY_GROUPS_PROC;
END LOAD_DATA_PACK;

 
/