CREATE OR REPLACE PACKAGE phenix.PHXJOBS_PACK IS

PROCEDURE START_AUTOMATED_LOG_PROC(
  p_module_name IN VARCHAR2,
  p_module_type IN VARCHAR2,
  p_message     IN VARCHAR2
);

PROCEDURE DETAIL_AUTOMATED_LOG_PROC(
  p_line_number IN NUMBER,
  p_message     IN VARCHAR2,
  p_error       IN VARCHAR2
);

PROCEDURE END_AUTOMATED_LOG_PROC(
  p_message IN VARCHAR2
);

END PHXJOBS_PACK;
/