CREATE OR REPLACE PACKAGE phenix.PRO_OPERATION_PACK IS

PROCEDURE BUILD_SYSTEM_OVERRIDE_PROC(
 p_pro_id    IN programs.pro_id%TYPE,
 p_paramList IN OUT SRW_PARAMLIST
);

FUNCTION FIND_PRINCIPAL_PRN_ID_FUNC(
  p_pro_name IN VARCHAR2
)
RETURN NUMBER;

END PRO_OPERATION_PACK;
/