CREATE OR REPLACE PACKAGE phenix.RADIO_BEACON_PACK IS

PROCEDURE RB_INITIAL_LOAD_PROC(
	p_prd_code IN VARCHAR2 := NULL
);

PROCEDURE RB_PICK_LIST_PROC(
 	p_plh_id IN NUMBER
);

END RADIO_BEACON_PACK;

 
/