CREATE OR REPLACE PACKAGE phenix.RECEIPT_MERCHANDISE_PACK IS

PROCEDURE CREATE_RHRDFILE_PROC(
	P_VENDOR_CODE   IN NUMBER,
	P_ORDER_NUMBER  IN VARCHAR2,
	P_ORDER_SOURCE  IN VARCHAR2,
	P_HEADER_DETAIL IN VARCHAR2   --nouveau parametre pour detail/header(HD) ou header(HH)
);

PROCEDURE READ_TMP_RC_FILE_PROC;

FUNCTION GET_RECALC_FREQUENCY
RETURN VARCHAR2;

END RECEIPT_MERCHANDISE_PACK;
/