CREATE OR REPLACE PACKAGE phenix.RMC_OPERATION_PACK IS

PROCEDURE INVOICE_RMC_PROC(
 p_jsc_id IN NUMBER
);

PROCEDURE UPDATE_DATE_BILLED_PROC(
  p_rmc_id IN recurring_misc_charges.rmc_id%TYPE
);

END RMC_OPERATION_PACK;
/