CREATE OR REPLACE PACKAGE phenix.SAS_OPERATION_PACK AS

FUNCTION COUNT_PHENIX_SESSIONS_FUNC
RETURN NUMBER;

PROCEDURE SET_ACTIVE_SESSION_PROC(
  p_sen_code IN system_environments.sen_code%TYPE,
  p_use_code IN users.use_code%TYPE
);

END SAS_OPERATION_PACK;
/