CREATE OR REPLACE PACKAGE phenix.SCA_OPERATION_PACK AS

FUNCTION GET_SCALE_WEIGHT_FUNC(
    p_sca_code  IN    SCALES.SCA_CODE%TYPE,
    p_dirty     OUT   BOOLEAN)
RETURN NUMBER;
FUNCTION EXIST_SCA_FUNC
RETURN BOOLEAN;

END SCA_OPERATION_PACK;
/