CREATE OR REPLACE PACKAGE phenix.SLI_OPERATION_PACK AS

FUNCTION COUNT_PHENIX_USERS_FUNC
RETURN NUMBER;

FUNCTION IS_TOO_MUCH_CONNECTIONS_FUNC(
  p_use_code IN users.use_code%TYPE
)
RETURN BOOLEAN;

END SLI_OPERATION_PACK;
/