CREATE OR REPLACE PACKAGE phenix.STAT_WILL_COMMSOLID_PACK  IS

PROCEDURE GEN_WILL_COMMSOLID_STATS_PROC(
 p_jsc_id IN NUMBER
);

PROCEDURE EXTRACT_WILL_COMMSOLID_PROC(
 p_from_date IN DATE,
 p_to_date   IN DATE,
 p_whs_code  IN VARCHAR2, --BER3573
 p_from_cus  IN NUMBER,   --BER6270
 p_to_cus    IN NUMBER,   --BER6270
 p_file_type IN VARCHAR2  --FRE4447
);
END STAT_WILL_COMMSOLID_PACK ;
/