CREATE OR REPLACE PACKAGE phenix.TRACEABILITY_OPERATION_PACK IS
PROCEDURE PASSPARTOUT_PRINT_PROC (
  p_type               IN  VARCHAR2,
 p_number_to_generate  IN NUMBER
);
END TRACEABILITY_OPERATION_PACK;
/