CREATE OR REPLACE PACKAGE phenix.TTPM_OPERATION_PACK IS

PROCEDURE BUILD_TTPM_PROC(
  p_whs_code  IN VARCHAR2,
  p_from_date IN DATE,
  p_to_date   IN DATE
);

PROCEDURE EXTRACT_TTPM_PROC(
  p_jsc_id   IN NUMBER
);

END TTPM_OPERATION_PACK;
/