CREATE OR REPLACE PACKAGE phenix.VENDOR_PACK IS

PROCEDURE FIND_VENDOR_ADDRESS_PROC
 (P_VENDOR_CODE IN NUMBER
 ,P_VENDOR_ADR_TYPE IN VARCHAR2
 ,P_SUSELANGUAGE IN VARCHAR2
 ,P_VENDOR_PRV_CODE OUT VARCHAR2
 ,P_VENDOR_ADDRESS OUT VARCHAR2
 ,P_VENDOR_CITY OUT VARCHAR2
 ,P_VENDOR_POSTAL_CODE OUT VARCHAR2
 ,P_VENDOR_TELEPHONE OUT NUMBER
 ,P_VENDOR_EXTENSION OUT NUMBER
 ,P_VENDOR_FAX_NUMBER OUT NUMBER
 );
END VENDOR_PACK;

 
/