CREATE OR REPLACE PACKAGE phenix.VENDOR_RETURNS_PACK IS

FUNCTION CREATE_INVOICE_FUNC(
  p_vbh_id  IN NUMBER,
  p_date    IN DATE DEFAULT NULL --CSC1256
)
RETURN NUMBER;

PROCEDURE INSERT_CONSIGNMENTS_PROC(
  p_vbh_id IN NUMBER,
  p_vbd_id IN NUMBER DEFAULT NULL
);

PROCEDURE VENDOR_RETURNS_PC_PROC( --BER78
  p_jsc_id IN NUMBER
);

--gic1700 procédure créer pour le SGE Phenix
PROCEDURE CREATE_TPC_VBD_TO_ZERO_PROC(
  p_log_id IN NUMBER
);

END VENDOR_RETURNS_PACK;
/