CREATE OR REPLACE PACKAGE phenix.VLM_OPERATION_PACK IS
PROCEDURE INSERT_CON_PROC(
  p_use_code                      IN NUMBER,
  p_module                        IN VARCHAR2,
  p_con_id                        IN NUMBER,
  p_con_cty_code                  IN VARCHAR2,
  p_con_first_name                IN VARCHAR2,
  p_con_last_name                 IN VARCHAR2,
  p_con_ven_cus_code              IN NUMBER,
  p_con_email                     IN VARCHAR2,
  p_con_extension                 IN NUMBER,
  p_con_extension_2               IN NUMBER,
  p_con_fax                       IN NUMBER,
  p_con_remark                    IN VARCHAR2,
  p_con_telephone                 IN NUMBER,
  p_con_telephone_2               IN NUMBER
  );
PROCEDURE DELETE_CON_PROC(
  p_use_code                      IN NUMBER,
  p_module                        IN VARCHAR2,
  p_con_id                        IN NUMBER,
  p_con_cty_code                  IN VARCHAR2,
  p_con_first_name                IN VARCHAR2,
  p_con_last_name                 IN VARCHAR2,
  p_con_ven_cus_code              IN NUMBER,
  p_con_email                     IN VARCHAR2,
  p_con_extension                 IN NUMBER,
  p_con_extension_2               IN NUMBER,
  p_con_fax                       IN NUMBER,
  p_con_remark                    IN VARCHAR2,
  p_con_telephone                 IN NUMBER,
  p_con_telephone_2               IN NUMBER
  );
PROCEDURE MODIF_CON_PROC(
  p_use_code                      IN NUMBER,
  p_module                        IN VARCHAR2,
  p_old_con_id                    IN NUMBER,
  p_old_con_cty_code              IN VARCHAR2,
  p_old_con_first_name            IN VARCHAR2,
  p_old_con_last_name             IN VARCHAR2,
  p_old_con_ven_cus_code          IN NUMBER,
  p_old_con_email                 IN VARCHAR2,
  p_old_con_extension             IN NUMBER,
  p_old_con_extension_2           IN NUMBER,
  p_old_con_fax                   IN NUMBER,
  p_old_con_remark                IN VARCHAR2,
  p_old_con_telephone             IN NUMBER,
  p_old_con_telephone_2           IN NUMBER,
  p_old_con_print_badge_report_s  IN NUMBER,
  p_new_con_cty_code              IN VARCHAR2,
  p_new_con_first_name            IN VARCHAR2,
  p_new_con_last_name             IN VARCHAR2,
  p_new_con_email                 IN VARCHAR2,
  p_new_con_extension             IN NUMBER,
  p_new_con_extension_2           IN NUMBER,
  p_new_con_fax                   IN NUMBER,
  p_new_con_remark                IN VARCHAR2,
  p_new_con_telephone             IN NUMBER,
  p_new_con_telephone_2           IN NUMBER
  );
FUNCTION CHECK_IF_CHANGED_VEN_FUNC(
  p_ven_code          IN NUMBER,
  p_mod_source        IN VARCHAR2,
  p_field_name        IN VARCHAR2,
  p_old_value         IN NUMBER,
  p_new_value         IN NUMBER,
  p_use_code          IN NUMBER DEFAULT 99999,
  p_address_type      IN VARCHAR2 DEFAULT NULL,
  p_category          IN VARCHAR2 DEFAULT NULL,
  p_whs_code          IN VARCHAR2 DEFAULT NULL,
  p_vlm_dit_code      IN NUMBER DEFAULT NULL,
  p_vlm_edi_code      IN NUMBER   DEFAULT NULL,
  p_vlm_vmt_id        IN NUMBER   DEFAULT NULL,
  p_vlm_con_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vwg_pgr_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vcl_id        IN NUMBER   DEFAULT NULL,
  p_vlm_tec_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vfe_fmt_code  IN VARCHAR2 DEFAULT NULL,
  p_vlm_dcs_cus_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vpra_id       IN NUMBER   DEFAULT NULL
) RETURN NUMBER;

FUNCTION CHECK_IF_CHANGED_VEN_FUNC(
  p_ven_code          IN NUMBER,
  p_mod_source        IN VARCHAR2,
  p_field_name        IN VARCHAR2,
  p_old_value         IN VARCHAR2,
  p_new_value         IN VARCHAR2,
  p_use_code          IN NUMBER DEFAULT 99999,
	p_address_type      IN VARCHAR2 DEFAULT NULL,
	p_category          IN VARCHAR2 DEFAULT NULL,
	p_whs_code          IN VARCHAR2 DEFAULT NULL,
	p_vlm_dit_code      IN NUMBER DEFAULT NULL,
  p_vlm_edi_code      IN NUMBER   DEFAULT NULL,
  p_vlm_vmt_id        IN NUMBER   DEFAULT NULL,
  p_vlm_con_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vwg_pgr_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vcl_id        IN NUMBER   DEFAULT NULL,
  p_vlm_tec_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vfe_fmt_code  IN VARCHAR2 DEFAULT NULL,
  p_vlm_dcs_cus_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vpra_id       IN NUMBER   DEFAULT NULL
) RETURN NUMBER;

FUNCTION CHECK_IF_CHANGED_VEN_FUNC(
  p_ven_code          IN NUMBER,
  p_mod_source        IN VARCHAR2,
  p_field_name        IN VARCHAR2,
  p_old_value         IN DATE,
  p_new_value         IN DATE,
  p_use_code          IN NUMBER DEFAULT 99999,
	p_address_type      IN VARCHAR2 DEFAULT NULL,
	p_category          IN VARCHAR2 DEFAULT NULL,
	p_whs_code          IN VARCHAR2 DEFAULT NULL,
	p_vlm_dit_code      IN NUMBER DEFAULT NULL,
  p_vlm_edi_code      IN NUMBER   DEFAULT NULL,
  p_vlm_vmt_id        IN NUMBER   DEFAULT NULL,
  p_vlm_con_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vwg_pgr_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vcl_id        IN NUMBER   DEFAULT NULL,
  p_vlm_tec_id        IN NUMBER   DEFAULT NULL,
  p_vlm_vfe_fmt_code  IN VARCHAR2 DEFAULT NULL,
  p_vlm_dcs_cus_code  IN NUMBER   DEFAULT NULL,
  p_vlm_vpra_id       IN NUMBER   DEFAULT NULL
) RETURN NUMBER;

END VLM_OPERATION_PACK;
/