CREATE OR REPLACE PACKAGE phenix.VPA_OPERATION_PACK IS

FUNCTION CHECK_USER_PARAM_FUNC(
  p_dpa_id IN NUMBER,
  p_value  IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION CHECK_STATEMENT_FUNC(
  p_jsc_id IN NUMBER,
  p_pro_id IN NUMBER
)
RETURN VARCHAR2;

FUNCTION CHECK_PARAM_FUNC(
  p_table IN VARCHAR2,
  p_sql   IN VARCHAR2,
  p_type  IN VARCHAR2,
  p_name  IN VARCHAR2
)
RETURN BOOLEAN;

FUNCTION CHECK_PRO_PARAM_FUNC(
  p_pro_id  IN programs.pro_id%TYPE,
  p_sql     IN VARCHAR2
)
RETURN BOOLEAN;

END VPA_OPERATION_PACK;
/