CREATE OR REPLACE PACKAGE phenix.WEB_SERVICES_PACK IS

FUNCTION SOAP_CALL
( p_payload    IN VARCHAR2
, p_target_url IN VARCHAR2
, p_soap_action IN VARCHAR2 DEFAULT 'process'
) RETURN XMLTYPE;

END WEB_SERVICES_PACK;
/