CREATE OR REPLACE FORCE VIEW phenix.v_prod_size_uom_lov (v_size_uom_code,v_uom_description,v_uom_alt_description) AS
SELECT 'AF' CODE, 'Centigramme' DESCRIPTION, 'Centigram' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'AM' CODE, 'Ampoule' DESCRIPTION, 'Ampoule' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'AR' CODE,
          'Suppositoire' DESCRIPTION,
          'Suppository' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'AV' CODE, 'Capsule' DESCRIPTION, 'Capsule' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'BF' CODE, 'Board Feet' DESCRIPTION, 'Board Feet' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'BG' CODE, 'Sac' DESCRIPTION, 'Bag' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'BO' CODE, 'Bouteille' DESCRIPTION, 'Bottle' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'BX' CODE, 'Boîte' DESCRIPTION, 'Box' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'C3' CODE, 'Centilitre' DESCRIPTION, 'Centiliter' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'CM' CODE, 'Centimètre' DESCRIPTION, 'Centimeter' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'DC' CODE, 'Disc' DESCRIPTION, 'Disk' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'DG' CODE, 'decigramme' DESCRIPTION, 'decigram' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'DL' CODE, 'Décilitre' DESCRIPTION, 'Deciliter' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'EA' CODE, 'Unité' DESCRIPTION, 'Each' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'FG' CODE,
          'Transdermal Patch' DESCRIPTION,
          'Transdermal Patch' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'FO' CODE, 'Once fluide' DESCRIPTION, 'Fluid Ounce' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'FZ' CODE,
          'Once fluide (imperial)' DESCRIPTION,
          'Fluid Ounce (imperial)' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'F2' CODE,
          'Unité internationale' DESCRIPTION,
          'International Unit' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'GN' CODE, 'Gallon ' DESCRIPTION, 'Gross Gallons' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'GR' CODE, 'Gramme' DESCRIPTION, 'Gram' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'IH' CODE, 'Inhaler' DESCRIPTION, 'Inhaler' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'KG' CODE, 'Kilogram' DESCRIPTION, 'Kilogramme' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'LB' CODE, 'Livre' DESCRIPTION, 'Pound' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'LT' CODE, 'Litre' DESCRIPTION, 'Litee' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'ME' CODE, 'Miligramme' DESCRIPTION, 'Milligram' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'ML' CODE, 'Millilitre' DESCRIPTION, 'Milliliter' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'MM' CODE, 'Millimètre' DESCRIPTION, 'Millimeter' ALT_DESCRIPTION
     FROM DUAL
   UNION
	 SELECT 'MR' CODE, 'Mètre' DESCRIPTION, 'Meter' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'OZ' CODE, 'Once - Av' DESCRIPTION, 'Ounce -AV' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'PC' CODE, 'Pièce' DESCRIPTION, 'Piece' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'PD' CODE, 'Pad' DESCRIPTION, 'Pad' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'PH' CODE, 'Paquet' DESCRIPTION, 'Pack (PAK)' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'PR' CODE, 'Pair' DESCRIPTION, 'Pair' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'QB' CODE,
          'Pages - Hardcopy' DESCRIPTION,
          'Pages - Hardcopy' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'RL' CODE, 'Rolls' DESCRIPTION, 'Rolls' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'SH' CODE, 'Sheet' DESCRIPTION, 'Sheet' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'ST' CODE, 'Ensemble' DESCRIPTION, 'Set' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'SZ' CODE, 'Seringue' DESCRIPTION, 'Syringe' ALT_DESCRIPTION
     FROM DUAL
   UNION
   SELECT 'TB' CODE, 'Tube' DESCRIPTION, 'Tube' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'U2' CODE, 'Tablet' DESCRIPTION, 'Tablet' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'UN' CODE, 'Unités' DESCRIPTION, 'Units' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'VI' CODE, 'Vial' DESCRIPTION, 'Vial' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'V2' CODE, 'Pouch' DESCRIPTION, 'Pouch' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'YD' CODE, 'Yard' DESCRIPTION, 'Yard' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT 'Y4' CODE, 'Tub' DESCRIPTION, 'Tub' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT '1N' CODE, 'Count' DESCRIPTION, 'Count' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT '12' CODE, 'Packet' DESCRIPTION, 'Packet' ALT_DESCRIPTION FROM DUAL
   UNION
   SELECT '15' CODE, 'Stick' DESCRIPTION, 'Stick' ALT_DESCRIPTION FROM DUAL;