CREATE OR REPLACE FORCE VIEW phenix.v_public_whse_transactions (pwtr_pwo_code,pwtr_pwo_name,pwtr_pwo_alt_name,pwtr_pwrh_id,pwtr_transaction_status,pwtr_pwrh_whs_code,pwtr_pwrh_po_number,pwtr_pwrh_receipt_number,pwtr_pwrh_project_recept_date,pwtr_pwrh_creation_date,pwtr_pwrh_site_number,pwtr_pwrh_account_id,pwtr_pwrh_enterprise_name,pwtr_pwrh_address,pwtr_pwrh_city,pwtr_pwrh_prv_code,pwtr_pwrh_postal_code,pwtr_pwrh_transport_method,pwtr_pwrh_scac_code,pwtr_pwrh_seal_number,pwtr_pwrh_seal_status,pwtr_pwrh_closed_switch,pwtr_pwrd_id,pwtr_pwrd_line_number,pwtr_pwrd_owner_product_code,pwtr_pwrd_format_code,pwtr_pwrd_product_description,pwtr_pwrd_quantity_ordered,pwtr_pwrd_rows_per_pallet,pwtr_pwrd_items_per_row,pwtr_pwrd_item_pack,pwtr_pwrd_vendor_product_code,pwtr_pwrd_upc_code,pwtr_pwid_id,pwtr_pwid_lot_code,pwtr_pwid_expiry_date,pwtr_pwid_identifier,pwtr_pwid_loc_code,pwtr_pwid_quantity,pwtr_pwid_use_reception_code,pwtr_pwid_reception_date,pwtr_pwid_pick_date,pwtr_pwid_use_pick_code,pwtr_pwpd_id,pwtr_pwpd_line_number,pwtr_pwpd_owner_product_code,pwtr_pwpd_format_code,pwtr_pwpd_product_description,pwtr_pwpd_quantity_to_pick,pwtr_pwpd_item_pack,pwtr_pwpd_vendor_product_code,pwtr_pwpd_upc_code,pwtr_pwph_id,pwtr_pwph_pwo_code,pwtr_pwph_whs_code,pwtr_pwph_picking_number,pwtr_pwph_requested_ship_date,pwtr_pwph_creation_date,pwtr_pwph_order_number,pwtr_pwph_site_number,pwtr_pwph_enterprise_name,pwtr_pwph_account_id,pwtr_pwph_address,pwtr_pwph_city,pwtr_pwph_prv_code,pwtr_pwph_postal_code,pwtr_pwph_transport_method,pwtr_pwph_closed_switch) AS
(
SELECT pwo.pwo_code pwtr_pwo_code,
        pwo.pwo_name pwtr_pwo_name,
        pwo.pwo_alt_name pwtr_pwo_alt_name,
        pwrh.pwrh_id pwtr_pwrh_id,
        (CASE WHEN pwrh.pwrh_closed_switch = 1 AND pwph.pwph_closed_switch IS NULL THEN 'RC' /*aucune transaction de cueillette encore..*/
              WHEN pwrh.pwrh_closed_switch = 1 AND pwph.pwph_closed_switch = 1 THEN 'PK' /*cest cueilli (et recu) */
              WHEN pwrh.pwrh_closed_switch = 1 AND pwph.pwph_closed_switch = 0 THEN 'RP' /*transaction de cueillette commencée mais pas terminée...*/
              WHEN pwrh.pwrh_closed_switch = 0 THEN 'OP' /*transaction de réception commencée mais pas terminée */
        END) pwtr_transaction_status,
        pwrh.pwrh_whs_code pwtr_pwrh_whs_code,
        pwrh.pwrh_po_number pwtr_pwrh_po_number,
        pwrh.pwrh_receipt_number pwtr_pwrh_receipt_number,
        pwrh.pwrh_project_reception_date pwtr_pwrh_project_recept_date,
        pwrh.pwrh_creation_date pwtr_pwrh_creation_date,
        pwrh.pwrh_site_number pwtr_pwrh_site_number,
        pwrh.pwrh_account_id pwtr_pwrh_account_id,
        pwrh.pwrh_enterprise_name pwtr_pwrh_enterprise_name,
        pwrh.pwrh_address pwtr_pwrh_address,
        pwrh.pwrh_city pwtr_pwrh_city,
        pwrh.pwrh_prv_code pwtr_pwrh_prv_code,
        pwrh.pwrh_postal_code pwtr_pwrh_postal_code,
        pwrh.pwrh_transport_method pwtr_pwrh_transport_method,
        pwrh.pwrh_scac_code pwtr_pwrh_scac_code,
        pwrh.pwrh_seal_number pwtr_pwrh_seal_number,
        pwrh.pwrh_seal_status pwtr_pwrh_seal_status,
        pwrh.pwrh_closed_switch pwtr_pwrh_closed_switch,
        pwrd.pwrd_id pwtr_pwrd_id,
        pwrd.pwrd_line_number pwtr_pwrd_line_number,
        pwrd.pwrd_owner_product_code pwtr_pwrd_owner_product_code,
        pwrd.pwrd_format_code pwtr_pwrd_format_code,
        pwrd.pwrd_product_description pwtr_pwrd_product_description,
        pwrd.pwrd_quantity_ordered pwtr_pwrd_quantity_ordered,
        pwrd.pwrd_rows_per_pallet pwtr_pwrd_rows_per_pallet,
        pwrd.pwrd_items_per_row pwtr_pwrd_items_per_row,
        pwrd.pwrd_item_pack pwtr_pwrd_item_pack,
        pwrd.pwrd_vendor_product_code pwtr_pwrd_vendor_product_code,
        pwrd.pwrd_upc_code pwtr_pwrd_upc_code,
        pwid.pwid_id pwtr_pwid_id,
        pwid.pwid_lot_code pwtr_pwid_lot_code,
        pwid.pwid_expiry_date pwtr_pwid_expiry_date,
        pwid.pwid_identifier pwtr_pwid_identifier,
        pwid.pwid_loc_code pwtr_pwid_loc_code,
        pwid.pwid_quantity pwtr_pwid_quantity,
        pwid.pwid_use_reception_code pwtr_pwid_use_reception_code,
        pwid.pwid_reception_date pwtr_pwid_reception_date,
        pwid.pwid_pick_date pwtr_pwid_pick_date,
        pwid.pwid_use_pick_code pwtr_pwid_use_pick_code,
        pwpd.pwpd_id pwtr_pwpd_id,
        pwpd.pwpd_line_number pwtr_pwpd_line_number,
        pwpd.pwpd_owner_product_code pwtr_pwpd_owner_product_code,
        pwpd.pwpd_format_code pwtr_pwpd_format_code,
        pwpd.pwpd_product_description pwtr_pwpd_product_description,
        pwpd.pwpd_quantity_to_pick pwtr_pwpd_quantity_to_pick,
        pwpd.pwpd_item_pack pwtr_pwpd_item_pack,
        pwpd.pwpd_vendor_product_code pwtr_pwpd_vendor_product_code,
        pwpd.pwpd_upc_code pwtr_pwpd_upc_code,
        pwph.pwph_id pwtr_pwph_id,
        pwph.pwph_pwo_code pwtr_pwph_pwo_code,
        pwph.pwph_whs_code pwtr_pwph_whs_code,
        pwph.pwph_picking_number pwtr_pwph_picking_number,
        pwph.pwph_requested_ship_date pwtr_pwph_requested_ship_date,
        pwph.pwph_creation_date pwtr_pwph_creation_date,
        pwph.pwph_order_number pwtr_pwph_order_number,
        pwph.pwph_site_number pwtr_pwph_site_number,
        pwph.pwph_enterprise_name pwtr_pwph_enterprise_name,
        pwph.pwph_account_id pwtr_pwph_account_id,
        pwph.pwph_address pwtr_pwph_address,
        pwph.pwph_city pwtr_pwph_city,
        pwph.pwph_prv_code pwtr_pwph_prv_code,
        pwph.pwph_postal_code pwtr_pwph_postal_code,
        pwph.pwph_transport_method pwtr_pwph_transport_method,
        pwph.pwph_closed_switch pwtr_pwph_closed_switch
FROM  public_whse_identifiers pwid,
      public_whse_receipt_details pwrd,
      public_whse_receipt_headers pwrh,
      public_whse_owners pwo,
      public_whse_pick_details pwpd,
      public_whse_pick_headers pwph
WHERE pwid.pwid_pwrd_id = pwrd.pwrd_id
  AND pwrd.pwrd_pwrh_id = pwrh.pwrh_id
  AND pwrh.pwrh_pwo_code = pwo.pwo_code
  AND pwid.pwid_pwpd_id = pwpd.pwpd_id (+)
  AND pwpd.pwpd_pwph_id = pwph.pwph_id (+)
);